import type { Metadata } from "next";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar"
import { AppSidebar } from "@/components/app-sidebar"
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SidebarProvider className="dark">
      <AppSidebar />
      <main className="w-full">
        <SidebarTrigger className="fixed text-white" />
        <div>
          {children}
        </div>
      </main>
    </SidebarProvider>
  );
}
